package apply

import (
	"bufio"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"syscall"
	"testing"
	"time"

	cataloguedata "github.com/headwalluk/foxtrainer/catalogue"
	"github.com/headwalluk/foxtrainer/internal/answers"
	"github.com/headwalluk/foxtrainer/internal/catalogue"
	"github.com/headwalluk/foxtrainer/internal/firefox"
	"github.com/headwalluk/foxtrainer/internal/sources/betterfox"
)

const pinnedBetterfoxDir = "../../testdata/upstream/betterfox/067172a4b0dc90e78e5b8b94d9abfe6430c6a7be"

// fixture is a throwaway profile plus the embedded catalogue and pinned upstream files.
type fixture struct {
	catalogue catalogue.Catalogue
	upstream  catalogue.Upstream
	target    Target
	options   Options
	clock     time.Time
}

// newFixture creates an empty profile folder with a Firefox-written prefs.js.
func newFixture(test *testing.T) *fixture {
	test.Helper()

	loaded, loadError := catalogue.Load(cataloguedata.Files)
	if loadError != nil {
		test.Fatal(loadError)
	}

	upstreamFiles := map[string][]betterfox.Record{}

	for _, fileName := range []string{"user.js", "Peskyfox.js"} {
		content, readError := os.ReadFile(filepath.Join(pinnedBetterfoxDir, fileName))
		if readError != nil {
			test.Fatal(readError)
		}

		records, parseError := betterfox.Parse(fileName, content)
		if parseError != nil {
			test.Fatal(parseError)
		}

		upstreamFiles[fileName] = records
	}

	profileDir := filepath.Join(test.TempDir(), "abcd1234.dev-edition-default-1")
	if mkdirError := os.MkdirAll(profileDir, 0o700); mkdirError != nil {
		test.Fatal(mkdirError)
	}

	created := &fixture{
		catalogue: loaded,
		upstream:  catalogue.Upstream{"betterfox": upstreamFiles},
		target: Target{
			InstallDir: "/usr/lib/firefox-devedition", ProfileDir: profileDir,
			Label: "Firefox Developer Edition 158.0 › dev-edition-default-1", FirefoxMajor: 158,
		},
		clock: time.Date(2026, 10, 2, 21, 0, 0, 0, time.UTC),
	}
	created.options = Options{
		StateDir: filepath.Join(test.TempDir(), "state"), FoxtrainerVersion: "0.4.0-test", Platform: "linux",
		Now: func() time.Time { created.clock = created.clock.Add(time.Second); return created.clock },
	}

	created.writeProfileFile(test, "prefs.js", "// Mozilla User Preferences\n\nuser_pref(\"browser.startup.page\", 3);\n")

	return created
}

// writeProfileFile writes a file into the fixture profile.
func (current *fixture) writeProfileFile(test *testing.T, name, content string) {
	test.Helper()

	if writeError := os.WriteFile(filepath.Join(current.target.ProfileDir, name), []byte(content), 0o600); writeError != nil {
		test.Fatal(writeError)
	}
}

// readProfileFile reads a file from the fixture profile.
func (current *fixture) readProfileFile(test *testing.T, name string) string {
	test.Helper()

	content, readError := os.ReadFile(filepath.Join(current.target.ProfileDir, name))
	if readError != nil {
		test.Fatal(readError)
	}

	return string(content)
}

// prepareAndCommit runs a full apply with chosen answers.
func (current *fixture) prepareAndCommit(test *testing.T, chosen answers.Answers) (Prepared, Committed) {
	test.Helper()

	prepared, prepareError := Prepare(current.catalogue, current.upstream, current.target, chosen, current.options)
	if prepareError != nil {
		test.Fatal(prepareError)
	}

	committed, commitError := Commit(prepared, current.options)
	if commitError != nil {
		test.Fatal(commitError)
	}

	return prepared, committed
}

// defaults are the agreed defaults for a new instance.
func defaults() answers.Answers {
	return answers.Answers{Feel: "balanced", AI: "off", Privacy: "strict", HTTPSOnly: true, Languages: []string{"en-GB"}}
}

func TestApplyLifecycle(test *testing.T) {
	current := newFixture(test)

	// 1. First apply on a fresh profile.
	first, firstCommit := current.prepareAndCommit(test, defaults())
	if len(first.Added) != first.PrefCount() || first.PrefCount() < 100 || len(first.ResetNames) != 0 {
		test.Errorf("first apply: added %d of %d, reset %v", len(first.Added), first.PrefCount(), first.ResetNames)
	}

	userJS := current.readProfileFile(test, "user.js")
	for _, expected := range []string{
		"generated by foxtrainer 0.4.0-test",
		"Betterfox 154.0 (commit 067172a4b0dc90e78e5b8b94d9abfe6430c6a7be)",
		"Copyright (c) 2020 yokoffing, MIT licence",
		`user_pref("browser.ai.control.default", "blocked"); // foxtrainer`,
		`user_pref("toolkit.telemetry.enabled", false); // betterfox user.js:123`,
	} {
		if !strings.Contains(userJS, expected) {
			test.Errorf("user.js is missing %q", expected)
		}
	}

	if info, statError := os.Stat(filepath.Join(current.target.ProfileDir, "user.js")); statError != nil || info.Mode().Perm() != 0o600 {
		test.Errorf("user.js mode: %v %v", info, statError)
	}

	if _, statError := os.Stat(filepath.Join(firstCommit.BackupDir, "prefs.js")); statError != nil {
		test.Errorf("prefs.js should be backed up: %v", statError)
	}

	// 2. Re-applying the same answers changes nothing.
	again, prepareError := Prepare(current.catalogue, current.upstream, current.target, defaults(), current.options)
	if prepareError != nil || again.UserJSChanged() || len(again.Added)+len(again.Changed)+len(again.Removed)+len(again.ResetNames) != 0 {
		test.Errorf("second apply should be a no-op: changed=%v %+v %v", again.UserJSChanged(), again.Changed, prepareError)
	}

	// Firefox runs and copies the user.js values into prefs.js.
	current.writeProfileFile(test, "prefs.js", "user_pref(\"browser.ml.enable\", false);\nuser_pref(\"browser.startup.page\", 3);\nuser_pref(\"browser.translations.enable\", false);\n")

	// 3. Switching AI to "all" removes the AI prefs from user.js and resets them in prefs.js.
	allAI := defaults()
	allAI.AI = "all"

	third, thirdCommit := current.prepareAndCommit(test, allAI)
	if !slices.Contains(third.Removed, "browser.ml.enable") || !slices.Contains(third.ResetNames, "browser.translations.enable") {
		test.Errorf("AI prefs should be removed and reset: removed=%v reset=%v", third.Removed, third.ResetNames)
	}

	if want := []string{"browser.ml.enable", "browser.translations.enable"}; !slices.Equal(thirdCommit.ResetInPrefs, want) {
		test.Errorf("reset in prefs.js: got %v, want %v", thirdCommit.ResetInPrefs, want)
	}

	if prefsJS := current.readProfileFile(test, "prefs.js"); prefsJS != "user_pref(\"browser.startup.page\", 3);\n" {
		test.Errorf("prefs.js after reset: %q", prefsJS)
	}

	manifest, manifestError := LoadManifest(current.options.StateDir, current.target.ProfileDir)
	if manifestError != nil || slices.Contains(manifest.Managed, "browser.ml.enable") || !slices.Contains(manifest.Managed, "toolkit.telemetry.enabled") {
		test.Errorf("manifest managed list: %v %v", manifest.Managed, manifestError)
	}
}

func TestApplyReplacesForeignUserJS(test *testing.T) {
	current := newFixture(test)
	current.writeProfileFile(test, "user.js", "// Betterfox\nuser_pref(\"gfx.webrender.layer-compositor\", true);\nuser_pref(\"broken\", ;\n")

	prepared, prepareError := Prepare(current.catalogue, current.upstream, current.target, defaults(), current.options)
	if prepareError != nil {
		test.Fatal(prepareError)
	}

	notes := strings.Join(prepared.Notes, "\n")
	if !strings.Contains(notes, "not written by foxtrainer") || !strings.Contains(notes, "unparseable") {
		test.Errorf("notes: %s", notes)
	}

	if !slices.Equal(prepared.Leftovers, []string{"gfx.webrender.layer-compositor"}) || len(prepared.ResetNames) != 0 {
		test.Errorf("leftovers %v, reset %v", prepared.Leftovers, prepared.ResetNames)
	}

	current.options.ResetPrevious = true

	withReset, resetError := Prepare(current.catalogue, current.upstream, current.target, defaults(), current.options)
	if resetError != nil || !slices.Contains(withReset.ResetNames, "gfx.webrender.layer-compositor") {
		test.Errorf("--reset-previous should reset leftovers: %v %v", withReset.ResetNames, resetError)
	}

	committed, commitError := Commit(withReset, current.options)
	if commitError != nil {
		test.Fatal(commitError)
	}

	backedUp, readError := os.ReadFile(filepath.Join(committed.BackupDir, "user.js"))
	if readError != nil || !strings.HasPrefix(string(backedUp), "// Betterfox") {
		test.Errorf("the old user.js must be backed up: %q %v", backedUp, readError)
	}
}

func TestApplyKeepsScopedExtensionsWorking(test *testing.T) {
	current := newFixture(test)
	scopedDir := filepath.Join(test.TempDir(), "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}")

	if mkdirError := os.MkdirAll(filepath.Join(scopedDir, "uBlock0@raymondhill.net"), 0o755); mkdirError != nil {
		test.Fatal(mkdirError)
	}

	current.options.ScopedExtensionDirs = []string{filepath.Join(test.TempDir(), "missing"), scopedDir}

	prepared, prepareError := Prepare(current.catalogue, current.upstream, current.target, defaults(), current.options)
	if prepareError != nil {
		test.Fatal(prepareError)
	}

	if strings.Contains(string(prepared.UserJS), enabledScopesPref) {
		test.Error("extensions.enabledScopes must be dropped when scoped extensions exist")
	}

	if !strings.Contains(strings.Join(prepared.Notes, "\n"), "kept extensions.enabledScopes") {
		test.Errorf("notes: %v", prepared.Notes)
	}
}

func TestApplyRecordsProfileGroupSharedPrefs(test *testing.T) {
	current := newFixture(test)

	prepared, _ := current.prepareAndCommit(test, defaults())
	if len(prepared.GroupShared) != 0 {
		test.Errorf("ungrouped profile reported group-wide prefs: %v", prepared.GroupShared)
	}

	current.target.ProfileGroupID = "7f1ff9e3"
	prepared, _ = current.prepareAndCommit(test, defaults())

	if !slices.Contains(prepared.GroupShared, "datareporting.healthreport.uploadEnabled") {
		test.Errorf("group-wide prefs: %v", prepared.GroupShared)
	}

	if slices.ContainsFunc(prepared.GroupShared, func(name string) bool { return !firefox.IsGroupSharedPref(name) }) {
		test.Errorf("non-shared pref listed as group-wide: %v", prepared.GroupShared)
	}

	if !strings.Contains(strings.Join(prepared.Notes, "\n"), "Profile Group (store 7f1ff9e3)") {
		test.Errorf("notes: %v", prepared.Notes)
	}

	manifest, loadError := LoadManifest(current.options.StateDir, current.target.ProfileDir)
	if loadError != nil {
		test.Fatal(loadError)
	}

	if manifest.ProfileGroupID != "7f1ff9e3" || !slices.Equal(manifest.GroupShared, prepared.GroupShared) {
		test.Errorf("manifest group record: %q %v", manifest.ProfileGroupID, manifest.GroupShared)
	}
}

func TestApplyRefusesSymlinkedUserJS(test *testing.T) {
	current := newFixture(test)
	realFile := filepath.Join(test.TempDir(), "dotfiles-user.js")

	if writeError := os.WriteFile(realFile, []byte("// mine\n"), 0o600); writeError != nil {
		test.Fatal(writeError)
	}

	if linkError := os.Symlink(realFile, filepath.Join(current.target.ProfileDir, "user.js")); linkError != nil {
		test.Fatal(linkError)
	}

	prepared, prepareError := Prepare(current.catalogue, current.upstream, current.target, defaults(), current.options)
	if prepareError != nil {
		test.Fatal(prepareError)
	}

	if _, commitError := Commit(prepared, current.options); commitError == nil || !strings.Contains(commitError.Error(), "symlink") {
		test.Errorf("want a symlink refusal, got %v", commitError)
	}
}

func TestBackupsArePruned(test *testing.T) {
	current := newFixture(test)
	current.options.KeepBackups = 3

	for _, feel := range []string{"lean", "balanced", "full", "lean", "balanced"} {
		chosen := defaults()
		chosen.Feel = feel
		current.prepareAndCommit(test, chosen)
	}

	_, unchanged := current.prepareAndCommit(test, func() answers.Answers { chosen := defaults(); chosen.Feel = "balanced"; return chosen }())
	if unchanged.BackupDir != "" {
		test.Errorf("a no-op apply must not create a backup: %s", unchanged.BackupDir)
	}

	entries, readError := os.ReadDir(filepath.Join(current.options.StateDir, "backups", InstanceKey(current.target.ProfileDir)))
	if readError != nil || len(entries) != 3 {
		test.Errorf("want 3 backups kept, got %d (%v)", len(entries), readError)
	}
}

// TestHelperProcessHoldsLock is not a real test: re-executed as a child, it holds the profile lock like Firefox.
func TestHelperProcessHoldsLock(test *testing.T) {
	if flag.NArg() != 1 {
		test.Skip("helper process only")
	}

	lockFile, openError := os.OpenFile(flag.Arg(0), os.O_RDWR|os.O_CREATE, 0o644)
	if openError != nil {
		test.Fatal(openError)
	}

	exclusive := syscall.Flock_t{Type: syscall.F_WRLCK, Whence: io.SeekStart}
	if lockError := syscall.FcntlFlock(lockFile.Fd(), syscall.F_SETLK, &exclusive); lockError != nil {
		test.Fatal(lockError)
	}

	fmt.Println("locked")

	if _, readError := io.ReadAll(os.Stdin); readError != nil {
		test.Fatal(readError)
	}
}

func TestApplyRefusesWhileFirefoxRuns(test *testing.T) {
	current := newFixture(test)

	helper := exec.CommandContext(test.Context(), os.Args[0], "-test.run=^TestHelperProcessHoldsLock$", "--",
		filepath.Join(current.target.ProfileDir, ".parentlock"))

	helperInput, inputError := helper.StdinPipe()
	if inputError != nil {
		test.Fatal(inputError)
	}

	helperOutput, outputError := helper.StdoutPipe()
	if outputError != nil {
		test.Fatal(outputError)
	}

	if startError := helper.Start(); startError != nil {
		test.Fatal(startError)
	}

	if readyLine, readError := bufio.NewReader(helperOutput).ReadString('\n'); readError != nil || readyLine != "locked\n" {
		test.Fatalf("helper did not lock: %q, %v", readyLine, readError)
	}

	prepared, prepareError := Prepare(current.catalogue, current.upstream, current.target, defaults(), current.options)
	if prepareError != nil {
		test.Fatal(prepareError)
	}

	_, commitError := Commit(prepared, current.options)

	if closeError := helperInput.Close(); closeError != nil {
		test.Error(closeError)
	}

	if waitError := helper.Wait(); waitError != nil {
		test.Error(waitError)
	}

	if !errors.Is(commitError, firefox.ErrProfileInUse) {
		test.Errorf("want ErrProfileInUse, got %v", commitError)
	}

	if _, statError := os.Stat(filepath.Join(current.target.ProfileDir, "user.js")); statError == nil {
		test.Error("nothing may be written while Firefox holds the profile")
	}
}
