package apply

import (
	"fmt"
	"sort"
	"strings"

	"github.com/headwalluk/foxtrainer/internal/answers"
	"github.com/headwalluk/foxtrainer/internal/catalogue"
	"github.com/headwalluk/foxtrainer/internal/prefs"
)

// generatedMarker identifies a user.js written by foxtrainer; it appears on the first line.
const generatedMarker = "generated by foxtrainer"

// HeaderInfo is what the user.js header records about how the file was built.
type HeaderInfo struct {
	FoxtrainerVersion string
	InstanceLabel     string // e.g. "Firefox Developer Edition 158.0 › dev-edition-default-1"
	Answers           answers.Answers
}

// RenderUserJS writes the plan as a user.js: a header with sources and credits, then one block per group.
//
// The output is deterministic: the same plan and header produce the same bytes, so an apply
// with nothing to change leaves the file alone.
func RenderUserJS(loaded catalogue.Catalogue, plan catalogue.Plan, header HeaderInfo) []byte {
	var builder strings.Builder

	fmt.Fprintf(&builder, "// user.js %s %s. Do not edit: `foxtrainer apply` rewrites this file.\n", generatedMarker, header.FoxtrainerVersion)
	builder.WriteString("// https://github.com/headwalluk/foxtrainer\n//\n")
	fmt.Fprintf(&builder, "// Instance:  %s\n", header.InstanceLabel)
	fmt.Fprintf(&builder, "// Answers:   feel=%s, ai=%s, privacy=%s, https_only=%t, languages=%s\n",
		header.Answers.Feel, header.Answers.AI, header.Answers.Privacy, header.Answers.HTTPSOnly, strings.Join(header.Answers.Languages, ","))
	fmt.Fprintf(&builder, "// Catalogue: %s\n", loaded.CatalogueVersion)

	for _, sourceID := range sortedSourceIDs(loaded) {
		source := loaded.Sources[sourceID]
		builder.WriteString("//\n// Built from:\n")
		fmt.Fprintf(&builder, "//   %s %s (commit %s)\n", source.Title, source.Tag, source.Commit)
		fmt.Fprintf(&builder, "//   %s. %s, %s licence.\n", source.Repository, source.Copyright, source.Licence)
		fmt.Fprintf(&builder, "//   This file is not %s; report problems to foxtrainer, not upstream.\n", source.Title)
	}

	for _, planned := range plan.Groups {
		if len(planned.Prefs) == 0 {
			continue
		}

		fmt.Fprintf(&builder, "\n// --- %s: %s\n", planned.Group.ID, planned.Group.Title)
		fmt.Fprintf(&builder, "// %s\n", planned.Group.Description)

		for _, pref := range planned.Prefs {
			fmt.Fprintf(&builder, "%s // %s\n", prefs.FormatUserPref(pref.Name, pref.Value), originComment(pref.Origin))
		}
	}

	return []byte(builder.String())
}

// originComment says where a pref's value came from.
func originComment(origin catalogue.Origin) string {
	comment := "foxtrainer"
	if origin.File != "" {
		comment = fmt.Sprintf("%s %s:%d", origin.Source, origin.File, origin.Line)
	}

	return comment
}

// sortedSourceIDs returns the catalogue's source IDs in order.
func sortedSourceIDs(loaded catalogue.Catalogue) []string {
	identifiers := make([]string, 0, len(loaded.Sources))
	for sourceID := range loaded.Sources {
		identifiers = append(identifiers, sourceID)
	}

	sort.Strings(identifiers)

	return identifiers
}

// IsGenerated reports whether a user.js was written by foxtrainer.
func IsGenerated(content []byte) bool {
	firstLine, _, _ := strings.Cut(string(content), "\n")

	return strings.Contains(firstLine, generatedMarker)
}

// ParseUserJS returns the user_pref values in a user.js, last one winning as in Firefox, and the
// numbers of lines that look like prefs but do not parse.
func ParseUserJS(content []byte) (map[string]prefs.Value, []int) {
	values := map[string]prefs.Value{}

	var badLines []int

	for index, line := range strings.Split(string(content), "\n") {
		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, "user_pref(") {
			continue
		}

		statement, parseError := prefs.ParseStatement(trimmed)
		if parseError != nil {
			badLines = append(badLines, index+1)

			continue
		}

		values[statement.Name] = statement.Value
	}

	return values, badLines
}
