package prefs

import (
	"reflect"
	"testing"
)

func TestRemoveUserPrefs(test *testing.T) {
	original := `// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.

user_pref("app.normandy.enabled", false);
user_pref("browser.ml.enable", false);
user_pref("browser.ml.enable.extra", true);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://example.com\",\"label\":\"user_pref(\\\"browser.ml.enable\\\", true);\"}]");
user_pref("browser.ml.chat.enabled",   false);
user_pref("unparseable", ;
user_pref("browser.ml.enable", true);
user_pref("toolkit.telemetry.enabled", false);`

	want := `// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.

user_pref("app.normandy.enabled", false);
user_pref("browser.ml.enable.extra", true);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://example.com\",\"label\":\"user_pref(\\\"browser.ml.enable\\\", true);\"}]");
user_pref("unparseable", ;
`

	cleaned, removed := RemoveUserPrefs([]byte(original), map[string]bool{
		"browser.ml.enable":         true,
		"browser.ml.chat.enabled":   true,
		"toolkit.telemetry.enabled": true,
		"never.present":             true,
	})

	if string(cleaned) != want {
		test.Errorf("cleaned content:\n%s\n--- want ---\n%s", cleaned, want)
	}

	wantRemoved := []string{"browser.ml.enable", "browser.ml.chat.enabled", "browser.ml.enable", "toolkit.telemetry.enabled"}
	if !reflect.DeepEqual(removed, wantRemoved) {
		test.Errorf("removed %v, want %v", removed, wantRemoved)
	}
}

func TestRemoveUserPrefsKeepsCRLFAndUntouchedFilesIdentical(test *testing.T) {
	original := "user_pref(\"a.keep\", 1);\r\nuser_pref(\"b.drop\", 2);\r\nuser_pref(\"c.keep\", 3);\r\n"

	cleaned, removed := RemoveUserPrefs([]byte(original), map[string]bool{"b.drop": true})
	if string(cleaned) != "user_pref(\"a.keep\", 1);\r\nuser_pref(\"c.keep\", 3);\r\n" || len(removed) != 1 {
		test.Errorf("got %q, %v", cleaned, removed)
	}

	unchanged, none := RemoveUserPrefs([]byte(original), map[string]bool{"zzz": true})
	if string(unchanged) != original || len(none) != 0 {
		test.Errorf("nothing to remove must leave the file byte-identical: %q", unchanged)
	}
}
